export enum NAVIGATION_ACTIONS {
    SET_CURRENT_INDEX = 'SET_CURRENT_INDEX',
    SET_IS_COLLAPSED = 'SET_IS_COLLAPSED',
}

export type NAVIGATION_ACTION_TYPES = {
    type: NAVIGATION_ACTIONS,
    payload: any
}

export type APP_ACTION_TYPES = NAVIGATION_ACTION_TYPES;